### ISSUE TITLE
[Bug] Setting set to None breaks the game

### ISSUE THREAD

**Issue by MathiusXII** [LinkTroisUn/ShipMeltdown#3]
There's a ton of console error spam and all object coords are set back to default.

**Comment by LinkTroisUn** [comment]
> There's a ton of console error spam and all object coords are set back to default.


Hello, I have never used LethalPipeRemoval. I tried to generate a meltdown with LethalPipeRemoval loaded, but nothing weird happened.
To debug this, I would need the log file after the errors occur, your LethalPipeRemoval config file, and to know what you did ingame for the errors to happen (related to LethalPipeRemoval)

**Comment by LinkTroisUn** [comment]
Since no answers have been given for a long time, I am closing this issue. You can still open it again if you manage to gather the required data

**Comment by MathiusXII** [comment]
Sorry I missed your response @LinkTroisUn. I just load a save and it's already broken.

[log.txt](https://github.com/user-attachments/files/15845079/log.txt)
[Hamster.LethalTubeRemoval.cfg.txt](https://github.com/user-attachments/files/15845080/Hamster.LethalTubeRemoval.cfg.txt)

**Comment by LinkTroisUn** [comment]
> [Error  : Unity Log] ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: key
Stack trace:
**UnityEngine.InputSystem.Keyboard.get_Item** (UnityEngine.InputSystem.Key key) (at <dbb0ce7b96144bd8bcbcb8b0d765f970>:IL_0013)
ShipMeltdown.Patches.StartOfRoundPatch.UpdatePatch () (at <1bb7d550de134051921d6a8c9bfd7dbe>:IL_0014)
(wrapper dynamic-method) StartOfRound.DMD<StartOfRound::Update>(StartOfRound)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<StartOfRound::Update>?-138409944(StartOfRound)
LethalThings.Patches.Debug.StartOfRound_Update (On.StartOfRound+orig_Update orig, StartOfRound self) (at O:/github/LethalThings/LethalThings/Patches/Debug.cs:200)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<StartOfRound::Update>?1005590056(StartOfRound)

I have started a new game with your config file, and everything went fine. However, the error spamming your logs comes from the keyboard inputs. Looks like the game can't find a precise key on your keyboard. Is your keyboard missing the F6 or F7 keys ? If the answer is yes, try changing the key of the **Toggle Emergency Lights** setting of ShipMeltdown's config file with another value that your keyboard has (to an unused key). Then, try launching the game again.

**Comment by MathiusXII** [comment]
Nope I've got 12 function keys up there...
Would my modlist help?

**Comment by LinkTroisUn** [comment]
Yes. If you can, also include a sharing code of your thunderstore/R2/else profile, so I can download the mods and their right version.

But still, try to change the setting I talked about earlier in ShipMeltdown's config. Change it to another button like F just to be sure wether the crash comes from that or not.

And last, are you playing in v50 or v49 ?

Edit : Also, what made you first think the problem was related to LethalPipeRemoval, and not ShipMeltdown itself only ?

**Comment by MathiusXII** [comment]
Ah... I think setting the key to "None" causes the issue too. I set it to "J" and it works fine.

**Comment by MathiusXII** [comment]
01902770-6142-150c-0663-b41f3b46af64
What's a R2/else profile?

Playing on v50

I thought it was a conflict with LethalPipeRemoval because it happens to reset the coords of that mod when this mod breaks.

**Comment by LinkTroisUn** [comment]
There are other mod managers, like r2modman, which is basically Thunderstore without Overwolf, and other that might be less known, for instance Gale. These other mod manager use profiles almost exactly the same way, so you can use the same profile sharing code and it will works with any of these.

I have good news and bad news. The good news are that now, the **ToggleEmergencyLights** setting set to None won't crash the game anymore. Instead, it will deactivates the associated functionnality. So, in a way, your issue is solved.

The bad news, however, are that while running the tests on your profile (nice one by the way), I stumbled on a critical incompatibility with PizzaProbability. I have spent 2.5+ hours trying different ways to avoid the incompatibility, but as PizzaProb's source code is not public, I ultimately did not succeed. The least I managed to do was, if Shipmeltdown detects PizzaProbability is there, it will try to deactivates it, so at least the game won't break when a meltdown start. This is not something I think I will be able to solve, or at least not soon.

I have published the new version on thunderstore.

**Comment by MathiusXII** [comment]
Ok thanks.

So there's no point anymore in having pizzaprobability and this mod installed at the same time?

**Comment by LinkTroisUn** [comment]
I've tried a few more workarounds to fix their incompatibility, but there is always something that goes wrong.

So, yes, there is no point in having these two mods at a same time, since they would break the meltdown when mixed together. Only one of them can be active at a time
