### ISSUE TITLE
Flashlights still stay red after meltdown

### ISSUE THREAD

**Issue by FrostyCirno** [LinkTroisUn/ShipMeltdown#4]
I dont know what else to write

![image](https://github.com/LinkTroisUn/ShipMeltdown/assets/107891678/0b59a028-a434-45d3-b0f9-cea2b1ec6249)

**Comment by LinkTroisUn** [comment]
I would need to know the following :

1) Does it concern only flashlights that were on ship when it took off ?

2) Do flashlights blink by themselves ?

3) Have the lights of the ship returned to their normal colours ?

4) Maybe the approximate time of when ship took off ? (2 min before explosion ? 15s  before ?)

If you can't answer all these questions now, you can still answer those for which you know the answer

**Comment by FrostyCirno** [comment]
1. It effects flashlights that were used during the meltdown and after the meltdown
2. The flashlights do blink
3. The ship lights returned to their normal colors
4. I tried both 1 minute and 15 seconds before the explosion

**Comment by FrostyCirno** [comment]
The video is a example of it during a meltdown, the screenshot was from a round after a meltdown
https://github.com/LinkTroisUn/ShipMeltdown/assets/107891678/ae469b81-7068-4af4-ba9a-bc2d284993a1

**Comment by LinkTroisUn** [comment]
I think I have found out why flashlights stayed red after the meltdown.
When the meltdown starts, one of the early step of the mod is to collect all the lights of the ship. Since I don't really know how to specifically get only the ones that belong to the ship, the mod ends up collecting more (such as flashlights).
For some reasons, some lights were collected twice or more, which messed the whole mechanism to restore their original color.

After adding another check, flashlights (and possibly other affected lights) should turn back to their original colour after the meltdown. Now, if you could test the latest push on the [FlashlightsStillRed](https://github.com/LinkTroisUn/ShipMeltdown/tree/FlashlightsStillRed) branch, so you can confirm that it indeed solves your issues. Here is the pre-compiled plugin folder : [ShipMeltdown.zip](https://github.com/user-attachments/files/15752564/ShipMeltdown.zip). It is a debug version, so a meltdown can be manually initiated by pressing the F7 key.

**Comment by FrostyCirno** [comment]
I tested the complied version you gave me. The flashlights sometimes would still change color, but going into orbit will always fix the color

**Comment by LinkTroisUn** [comment]
I don't know how I can prevent flashlights from changing the colors of their lights, but at least, now, they get back to normal after the meltdown.

I have published the new version on Thunderstore.
